### ISSUE TITLE
receivePush() 가 반응이 없습니다.

### ISSUE THREAD

**Issue by YongHoonYun** [BOXOUT-THINKERS/TiOpenChat#1]
안녕하세요 !

해당 소스의 parse / push 를 테스트 해보았습니다만, parse에서 푸쉬를 보내면 노티까지는 정상적으로 출력됩니다만, 전달 받은 데이터를 후 처리 하려고 했는데, receivePush() 로 전달이 안 되는 것 같습니다.
혹시 진입이 안되는가 해서 ParsePush.addEventListener('notification... 리스너 부분에도 Alert과 로그를 찍어봤습니다만, 반응이 없습니다.

parsepush.js 에 관련된 소스와 모듈을 붙였습니다.
제가 놓친 부분이 있을까요 ?

**Comment by gimdongwoo** [comment]
답변 드릴 내용을 떠올리지 못해서 답변을 안달고 있었는데 해결하셨어요?

**Comment by YongHoonYun** [comment]
네 ! 해결되었습니다. 워낙 원초적인 실수라..
Parse 를 여러곳에서 쓰다보니 좀 꼬였던거 같습니다.
클라이언트키 와 CreateController 선언부를 조정해주니 해결되었습니다.
이제 후처리를 해야겠네요 ! 감사합니다 ㅎ
