### ISSUE TITLE
IOS Firebase 모듈 이식 후, 오류 발생

### ISSUE THREAD

**Issue by YongHoonYun** [BOXOUT-THINKERS/TiOpenChat#2]
안녕하세요 !
채팅 관련 부분을 연동하고 있습니다.
IOS 도 연동을 하려고 모듈을 넣어주고 require 했는데, new 하면 하기 오류가 발생합니다.

[ERROR] [iphone, 9.2, 192.168.0.159] {
  "message": "**\* -[__NSCFString substringToIndex:]: Index 9223372036854775806 out of bounds; string length 60",
  "line": 47,
  "sourceURL": "file:///Users/stylemirror/Library/Developer/CoreSimulator/Devices/319DB596-0B6A-4CB8-B22A-A926F791BFB3/data/Containers/Bundle/Application/9FCB02EB-FC5B-4AFE-A8EB-5DD0FCCB9E2A/lime-test.app/com.leftlanelab.firebase",
  "column": 74,
  "stack": "[native code]\non@file:///Users/stylemirror/Library/Developer/CoreSimulator/Devices/319DB596-0B6A-4CB8-B22A-A926F791BFB3/data/Containers/Bundle/Application/9FCB02EB-FC5B-4AFE-A8EB-5DD0FCCB9E2A/lime-test.app/com.leftlanelab.firebase:47:74\nlistenStart\n\n"
}

위 오류의 원인이 될 만한 곳이 있을까요 ?

**Comment by YongHoonYun** [comment]
자답입니다.

properies Firebase_AppUrl 값에 시뮬레이터 항목에 있는 Url 값을 넣고 키를 config에 설정해주니 해결됩니다.

**Comment by gimdongwoo** [comment]
iOS가 좀 내용도 없이 막 죽고 그래서 개발하기 어려운 면이 있죠.
아무래도  Objective C라서 그런거 같아요.
지도 모듈을 iOS에 적용할 때 막 시도 때도 없이 막 죽고 그러거든요...
