### ISSUE TITLE
Firebase 설정값 문의

### ISSUE THREAD

**Issue by YongHoonYun** [BOXOUT-THINKERS/TiOpenChat#3]
안녕하세요 !
열씸히 채팅과 푸쉬를 붙이고 있습니다.

Firebase 를 연동하는 도중에 몇가지 궁금한 점이 생겨서 문의드립니다.

connect 함수를 보면 path / url / key 를 가지고 init을 시키고 있는데, 실제 properties와 config에 설정된 값을 보면, path = '/' , ulr = (웹파이어베이스의 secret code), key = '' 로 되어 있습니다.

혹시 따로 키값이나 path를 설정해야 하는지 문의드립니다.
설정하는 방법이 리뷰에 없는 것 같아 간단히 가이드가 가능하시면 부탁 드립니다.

항상 감사합니다 ! 수고하세요 !

**Comment by gimdongwoo** [comment]
보안상 api key를 이용해야하는게 맞는데, 구현 편의상 url 로만 주면 동작하도록 했습니다.
firebase 에서 익명 접속 허용이 기본 값일 텐데 그래서 별다른 설정 없이 동작합니다.
(firebase 정책이 바뀌었으면 인증을 꺼주어야 할거에요)
